- name : "Configuring Master Node"  
  hosts : tag_Name_master
  vars :
    ip : 0.0.0.0
    dir : /master
    node : name

  tasks :
    - name : "Copying jdk to the master"
      copy : 
        src : jdk-8u171-linux-x64.rpm
        dest : /root

    - name : "Copying Hadoop 1.12 to the master"
      copy : 
        src : hadoop-1.2.1-1.x86_64.rpm
        dest : /root

    - name : "Installing Jdk"
      command : rpm -i /root/jdk-8u171-linux-x64.rpm
      ignore_errors : yes

    - name : "Installing Hadoop ver 1.2"
      command : rpm -i /root/hadoop-1.2.1-1.x86_64.rpm --force
      ignore_errors : yes

    - name : "Creating Metadata folder"
      file : 
        dest : "{{dir}}"
        state : directory

    - name : "Transfering hdfs conf file"
      template :
        src : hdfs-site.xml.j2 
        dest : /etc/hadoop/hdfs-site.xml

    - name : "Transfering core-site conf file"
      template :
        src : core-site.xml.j2
        dest : /etc/hadoop/core-site.xml
    
    - name : "Formating the file system"
      command : pwd

    - name : "Starting the namenode"
      command : pwd
    

- name : "Configuring Slave Node"
  hosts : tag_Name_slave
  vars :
    node : data
    dir : /slave

  vars_prompt :
    - name: ip
      prompt : "Please Enter the Ip of Master Node"
      private : no

  tasks :
    - name : "Copying jdk to the slave"
      copy : 
        src : jdk-8u171-linux-x64.rpm
        dest : /root

    - name : "Copying Hadoop 1.12 to the slave"
      copy : 
        src : hadoop-1.2.1-1.x86_64.rpm
        dest : /root

    - name : "Installing Jdk"
      command : rpm -i /root/jdk-8u171-linux-x64.rpm
      ignore_errors : yes

    - name : "Installing Hadoop ver 1.2"
      command : rpm -i /root/hadoop-1.2.1-1.x86_64.rpm --force
      ignore_errors : yes

    - name : "Creating Shared folder"
      file : 
        dest : "{{dir}}"
        state : directory

    - name : "Transfering hdfs conf file"
      template :
        src : hdfs-site.xml.j2 
        dest : /etc/hadoop/hdfs-site.xml

    - name : "Transfering core-site conf file"
      template :
        src : core-site.xml.j2
        dest : /etc/hadoop/core-site.xml

    - name : "Starting the datanode"
      command : hadoop-daemon.sh start datanode
      
